version: "3"

services:
  api:
    build: .
    ports:
      - 3123:3123
    volumes:
      - .env:/src/.env:ro
    environment:
      - GIN_MODE=release
    command: ./api
    restart: unless-stopped

# vim: ts=2 sw=2
