version: "3"

services:
  verlichting-api:
    build: .
    ports:
      - 3123:3123
    volumes:
      - .env:/src/.env:ro
    environment:
      - GIN_MODE=release
    networks:
      - local_verlichting_network
    restart: unless-stopped

networks:
    local_verlichting_network:
      driver: bridge
      ipam:
        config:
        - subnet:  10.0.140.0/24

# vim: ts=2 sw=2
