version: "3"

services:
  api:
    build: .
    ports:
      - 3000:3000
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./src:/src
      - ./dotenv:/src/.env:ro
